name: Denny zber dat do archivu

on:
  schedule:
    - cron: '57 23 * * *' # Každý deň o 23:57
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Stiahnutie repozitára
        uses: actions/checkout@v4

      - name: Nastavenie Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Inštalácia knižníc
        run: pip install pandas requests

      - name: Spustenie denného zberu
        run: python meteo_zber_v2.py

      - name: Uloženie zmien do archívu
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add meteo_puste_pole_v2.csv
          git commit -m "Denny zber do meteo_puste_pole_v2.csv" || echo "Žiadne zmeny"
          git push
