name: Denný meteo zápis

on:
  schedule:
    - cron: '57 23 * * *'  # Spustí sa každý deň presne o 23:57
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Stiahnutie repozitára
        uses: actions/checkout@v4

      - name: Nastavenie Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Inštalácia knižníc
        run: pip install -r requirements.txt

      - name: Spustenie denného zberu
        run: |
          python meteo_zber_v2.py

      - name: Automatické uloženie a odoslanie zmien na GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add meteo_puste_pole_v2.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Denný meteo zápis o 23:57" && git push)