name: Aktualizácia počasia

on:
  schedule:
    - cron: '*/15 * * * *' # Každých 15 minút
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Stiahnutie repozitára
        uses: actions/checkout@v4

      - name: Nastavenie Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Inštalácia knižníc a prehliadača pre Playwright
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Spustenie zberu dát
        run: python update_weather.py

      - name: Automatické uloženie a odoslanie zmien
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add meteo_aktualne.csv
          git commit -m "Auto aktualizácia meteo_aktualne.csv" || echo "Žiadne zmeny"
          git push
